# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'kullanici_paneli.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Kullanici_paneli(object):
    def setupUi(self, Kullanici_paneli):
        Kullanici_paneli.setObjectName("Kullanici_paneli")
        Kullanici_paneli.resize(839, 696)
        Kullanici_paneli.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        Kullanici_paneli.setMouseTracking(True)
        self.centralwidget = QtWidgets.QWidget(Kullanici_paneli)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(50, 130, 741, 531))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.frame_degiskeni = QtWidgets.QLabel(self.tab)
        self.frame_degiskeni.setGeometry(QtCore.QRect(50, 0, 641, 461))
        self.frame_degiskeni.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.frame_degiskeni.setMouseTracking(False)
        self.frame_degiskeni.setText("")
        self.frame_degiskeni.setObjectName("frame_degiskeni")
        self.layoutWidget = QtWidgets.QWidget(self.tab)
        self.layoutWidget.setGeometry(QtCore.QRect(250, 470, 241, 30))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.basla = QtWidgets.QPushButton(self.layoutWidget)
        self.basla.setStyleSheet("color: rgb(0, 255, 0);")
        self.basla.setObjectName("basla")
        self.horizontalLayout.addWidget(self.basla)
        self.sonlandir = QtWidgets.QPushButton(self.layoutWidget)
        self.sonlandir.setStyleSheet("color: rgb(255, 0, 0);")
        self.sonlandir.setObjectName("sonlandir")
        self.horizontalLayout.addWidget(self.sonlandir)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.label_2 = QtWidgets.QLabel(self.tab_2)
        self.label_2.setGeometry(QtCore.QRect(110, 20, 521, 371))
        self.label_2.setText("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600; font-style:italic; color:#000000;\">ISPARTA UYGULAMALI BİLİMLER ÜNİVERSİTESİ<br />BİLGİSAYAR MÜHENDİSLİĞİ BÖLÜMÜ<br />BİTİRME TEZİ PROJESİ</span></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt; font-style:italic; color:#55aaff;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; color:#55aaff;\"><br /></span></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt; color:#55aaff;\"><br /></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt; color:#55aaff;\"><br /></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt; color:#55aaff;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; color:#55aaff;\">Merhabalar. Kullanmakta olduğunuz uygulama <br />\'DERİN ÖĞRENME İLE ATIK TESPİTİ\' <br />projesi kapsamında geliştrilmiştir.  <br /><br /><br /></span></p></body></html>")
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(self.tab_2)
        self.label.setGeometry(QtCore.QRect(290, 100, 171, 181))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("1595336542606.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(self.tab_2)
        self.label_3.setGeometry(QtCore.QRect(530, 440, 201, 61))
        self.label_3.setText("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; color:#55aaff;\">DANIŞMAN<br />DOÇ. DR. Sinan UĞUZ</span></p></body></html>")
        self.label_3.setObjectName("label_3")
        self.label_6 = QtWidgets.QLabel(self.tab_2)
        self.label_6.setGeometry(QtCore.QRect(0, 440, 171, 51))
        self.label_6.setText("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; color:#55aaff;\">GELİŞTİREN<br />Ömer SOYDİNÇ</span></p></body></html>")
        self.label_6.setObjectName("label_6")
        self.label_8 = QtWidgets.QLabel(self.tab_2)
        self.label_8.setGeometry(QtCore.QRect(170, 380, 421, 91))
        self.label_8.setText("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">&quot;Derin Öğrenme İle Atık Tespiti&quot; projemiz </span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">\'TÜBİTAK 2209-A\' ve \'Teknofest Çevre ve Enerji Teknolojileri\' </span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">yarışmalarına uyarlanılarak başvuruları yapılmıştır.</span><span style=\" font-family:\'Poppins\',\'Helvetica\',\'sans-serif\'; font-size:13px; font-weight:600; color:#181c32; background-color:#ffffff;\"> </span></p></body></html>")
        self.label_8.setObjectName("label_8")
        self.tabWidget.addTab(self.tab_2, "")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(270, 40, 291, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label_4.setFont(font)
        self.label_4.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label_4.setObjectName("label_4")
        self.horizontalLayoutWidget_8 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_8.setGeometry(QtCore.QRect(790, 90, 51, 611))
        self.horizontalLayoutWidget_8.setObjectName("horizontalLayoutWidget_8")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_8)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.horizontalLayoutWidget_9 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_9.setGeometry(QtCore.QRect(0, 90, 51, 611))
        self.horizontalLayoutWidget_9.setObjectName("horizontalLayoutWidget_9")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_9)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.horizontalLayoutWidget_12 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_12.setGeometry(QtCore.QRect(50, 90, 741, 41))
        self.horizontalLayoutWidget_12.setObjectName("horizontalLayoutWidget_12")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_12)
        self.horizontalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.horizontalLayoutWidget_10 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_10.setGeometry(QtCore.QRect(50, 660, 741, 41))
        self.horizontalLayoutWidget_10.setObjectName("horizontalLayoutWidget_10")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_10)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(0, 0, 131, 91))
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap("../Tez Kodlar/foto/logo.png"))
        self.label_7.setScaledContents(True)
        self.label_7.setOpenExternalLinks(False)
        self.label_7.setObjectName("label_7")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(740, 0, 101, 91))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("../Tez Kodlar/foto/images.png"))
        self.label_5.setScaledContents(True)
        self.label_5.setOpenExternalLinks(False)
        self.label_5.setObjectName("label_5")
        self.horizontalLayoutWidget_15 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_15.setGeometry(QtCore.QRect(0, 0, 281, 41))
        self.horizontalLayoutWidget_15.setObjectName("horizontalLayoutWidget_15")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_15)
        self.horizontalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.horizontalLayoutWidget_16 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_16.setGeometry(QtCore.QRect(560, 0, 281, 41))
        self.horizontalLayoutWidget_16.setObjectName("horizontalLayoutWidget_16")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_16)
        self.horizontalLayout_19.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        Kullanici_paneli.setCentralWidget(self.centralwidget)

        self.retranslateUi(Kullanici_paneli)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Kullanici_paneli)

    def retranslateUi(self, Kullanici_paneli):
        _translate = QtCore.QCoreApplication.translate
        Kullanici_paneli.setWindowTitle(_translate("Kullanici_paneli", "MainWindow"))
        self.basla.setText(_translate("Kullanici_paneli", "Başla"))
        self.sonlandir.setText(_translate("Kullanici_paneli", "Sonlandır"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Kullanici_paneli", "ATIK TESPİTİ EKRANI"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Kullanici_paneli", "HAKKIMIZDA"))
        self.label_4.setText(_translate("Kullanici_paneli", " ATIK YÖNETİM SİSTEMİ "))
